# Generated by Django 2.2.9 on 2020-01-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_car_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='lizzcustomfield',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
